import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  DB_HOST: Joi.string().default('localhost'),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_EXPIRATION: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRATION: Joi.string().default('7d'),
  CONFIRMATION_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  PASSWORD_RESET_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  MAIL_HOST: Joi.string().default('mailpit'),
  MAIL_PORT: Joi.number().default(1025),
  MAIL_FROM: Joi.string().default('"StreamTube" <noreply@streamtube.com>'),
  SWAGGER_ENABLED: Joi.string().valid('true', 'false').default('false'),
  QUEUE_HOST: Joi.string().default('valkey'),
  QUEUE_PORT: Joi.number().default(6379),
  QUEUE_SWEEP_ABANDONED_UPLOADS_INTERVAL_MS: Joi.number().default(3600000),
  STORAGE_ENDPOINT: Joi.string().uri().default('http://storage:9000'),
  STORAGE_REGION: Joi.string().default('us-east-1'),
  STORAGE_ACCESS_KEY_ID: Joi.string().required(),
  STORAGE_SECRET_ACCESS_KEY: Joi.string().required(),
  STORAGE_VIDEOS_BUCKET: Joi.string().default('streamtube-videos'),
  STORAGE_THUMBNAILS_BUCKET: Joi.string().default('streamtube-thumbnails'),
  STORAGE_PRESIGNED_UPLOAD_URL_TTL_SECONDS: Joi.number().default(3600),
  STORAGE_PRESIGNED_STREAM_URL_TTL_SECONDS: Joi.number().default(300),
  STORAGE_PRESIGNED_DOWNLOAD_URL_TTL_SECONDS: Joi.number().default(900),
  STORAGE_UPLOAD_ABANDONED_TTL_SECONDS: Joi.number().default(86400),
  UPLOAD_MAX_FILE_SIZE_BYTES: Joi.number().default(10737418240),
  UPLOAD_ACCEPTED_MIME_TYPES: Joi.string().default(
    'video/mp4,video/webm,video/quicktime',
  ),
  STORAGE_MULTIPART_PART_SIZE_BYTES: Joi.number().default(104857600),
  STORAGE_TEST_KEY_PREFIX: Joi.string().default('test/'),
});
